version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "fastlane"
      - dependency-name: "cocoapods"
      - dependency-name: "generamba"
    assignees:
      - "ivan-magda"
    commit-message:
      prefix: "bundler"
    labels:
      - "dependencies"
    rebase-strategy: "disabled"
    target-branch: "dev"
